### ISSUE TITLE
Windows Installation Fails While Installing pyinotify: inotify is not available on win-amd64

### ISSUE THREAD

**Issue by moigagoo** [moyaproject/moya#2]
Hi!

running `pip install moya` on Windows fails with this message::

```inotify is not available on win-amd64```

inotify is a Linux program, not available on Windows. Moya requires pyinotify, which is, apparently, available only for Linux (https://github.com/seb-m/pyinotify#dependencies)

However, you state that Moya should run on Windows (http://docs.moyaproject.com/0.5/en/installation.html#windows).

Is there a workaround available?

Thanks!

**Comment by willmcgugan** [comment]
Hi,

I've just pushed version 0.5.3, which fixes that and a few other issues. It should run on Windows now. Let me know if works for you...

Will

**Comment by moigagoo** [comment]
Thanks! Installed like a charm. The only quirk is that lxml has to be installed separately, but that's no problem with these wheels http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

Thanks again!

**Comment by willmcgugan** [comment]
Great. lxml is a pain on Linux as well. Will add that to the docs.
