### ISSUE TITLE
Windows: `moya runserver` runs but raises exception

### ISSUE THREAD

**Issue by moigagoo** [moyaproject/moya#4]
Here's the traceback:

```[27/Feb/2015 10:59:30]:moya.startup:DEBUG: failed to watch Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Konstantin\appdata\local\scoop\apps\python\3.4.2\Lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Users\Konstantin\Projects\moya\lib\site-packages\fs\osfs\watch_win32.py", line 353, in run
    self._iocp = CreateIoCompletionPort(INVALID_HANDLE_VALUE,None,0,1)
  File "C:\Users\Konstantin\Projects\moya\lib\site-packages\fs\osfs\watch_win32.py", line 72, in _errcheck_handle
    raise ctypes.WinError()
OSError: [WinError 6] The handle is invalid.```

**Important**: The server site still runs OK despite this message.

**Comment by willmcgugan** [comment]
That's the auto-reload thread. I can't reproduce that on my Windows 7 machine. What version of Windows are you running?

**Comment by moigagoo** [comment]
I'm on Windows 10 Tech Preview with Python 3. Windows 10 should behave similarly to Windows 8.1 though.

**Comment by willmcgugan** [comment]
I've made some changes that *may* fix this. Although I still don't have WIndows 10 here, but it works on Windows 7/8. Would you mind testing again?

**Comment by moigagoo** [comment]
Hi! The warning is no more there, thanks!

BTW, Moya is a total kickass. Unfortunately, I hadn't had much time experimenting with it, but what I've seen is fantastic.

**Comment by willmcgugan** [comment]
Good to know, thanks! Let me know if you have any questions.
